### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by talamortis** [talamortis/Wildhammerbug#10]
- [x] Paladin's to learn 1- Handed Swords.
- [x] Grandmaster Vorpil Voild Walker speed Reduced
- [x] Shadow Labs Skeletons Visual Bug
- [x] SouthSea FootLockers to Attack (Shoot)
- [x] Gravis Slipknot Dispaly ID changed
- [x] Rune Strike Does not proc on Parry/ Dodge
- [x] Coilfang Emissary Remove Item (primed-key-mold) ID 31239, 31241
- [x] Scarlet Monastery - Mograin should be killable.
- [x]  Urisus Should spawn
- [x] Magisters Terrace Kael'thas Phase 2

**Comment by talamortis** [comment]
All paladins should learn One-Handed Swords on character creation
