### ISSUE TITLE
Todo list #2

### ISSUE THREAD

**Issue by talamortis** [talamortis/Wildhammerbug#14]
- [x] Shadow labs creatures respawn
- [x] Complete creature respawn of deadmines instance
- [x] Fix the reputation for quest "Ally of the Netherdrake"
- [x] Shadow labs creatures are casting renew when shouldnt have the spell
- [x] Spawn more nodes in netherstorm (herb)
- [ ] Wing Commander Ichman  check Waypoints.
- [x] Last Player in RDF does not leave party.
